# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79327ef8a7e9b21fcb1cb710e96c908d97a1a2262dca9b9b16958ac18edc2a2e5ed044e7cc4a8a17ad2e1f14541761a37d8ccc0d3483a35b5e569acdec2e673c

test:
  secret_key_base: 9311dcc98e59a6e5350dd59992a1aceaf8334c381a5c7531d76c656b4fb8f384c6046ebd432a08e1dedb0124e74021ce6dddd4148bdb7bc0d459eae1c37bd926

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
